AllCops:
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'lib/tasks/*'
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'

Metrics/LineLength:
  Description: Limit lines to 100 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 100
  AllowURI: true
  Exclude:
    - config/**/*.rb
    - spec/views/**/*.rb
  URISchemes:
    - http
    - https

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: ~

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

# Style/GuardClause:
#   Description: Check for conditionals that can be replaced with guard clauses
#   StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-nested-conditionals
#   Enabled: true
#   MinBodyLength: 3 # 1 is the default
